Imagenes remotas de descuentos y constantes de UI
juansanzone/MLBusinessComponents pull request #3
Opened 2019-09-03 14:56 UTC by eboffa

Se obtienen la imágenes remotas de descuentos y se agregan las constantes de UI

2019-09-03 23:24 UTC, juansanzone requested changes

2019-09-03 23:24 UTC, juansanzone commented on MLBusinessComponents/Source/Components/Discount/MLBusinessDiscountSingleItemView.swift
> +            icon.heightAnchor.constraint(equalToConstant: UI.Size.M_SIZE),
Para este caso no usemos el valor de M o algo así. Sino especificamente una dimensión relacionada con el heightWidth del icono de descuento. ¿Me explico? Y lo mismo arriba cuando aplicamos el corner radius.

2019-09-03 23:24 UTC, juansanzone commented on MLBusinessComponents/Source/Core/UIConstants.swift
> +        static let placeHolderColor: UIColor = "efefef".hexaToUIColor()
Cambiar ese color por esto: @eboffa 
UIColor(red:0.94, green:0.94, blue:0.94, alpha:1.0)

2019-09-03 23:44 UTC, eboffa commented on MLBusinessComponents/Source/Core/UIConstants.swift
> +        static let placeHolderColor: UIColor = "efefef".hexaToUIColor()
Listo @juansanzone

2019-09-04 00:00 UTC, juansanzone approved these changes

2019-09-04 00:00 UTC, juansanzone commented
💃 mergealo 💃  @eboffa

2019-09-04 12:12 UTC, merged